#meer icons komen soon, momenteel alleen de diamond.

login-message: "Geen"
logout-message: "Geen"
commandspy: "Aan"

Autobroadcast:
  Enabled: "True" #alleen True of False (ja & nee)
  Messages:
    - "&7Deze plugin is gemaakt door &6TacticalDev&7."
    - "&7Deze plugin kunt u vinden op spigot."
    - "&7Deze plugin is &6'100%' &7gratis."
  Timer: 160

Items:
  Whitelist:
    Name: "&6Whitelist"
    Types:
      Aan:
        Name: "&c%diamond% &aAan"
      Uit:
        Name: "&c%diamond% &4Uit"
  Players:
    Name: "&6Players"
    SkullOwner: "TacticalDev" #DIT KAN ALLE SKINS BEVATTEN, INCLUSIEF LINKS
  OPPlayers:
    Name: "&6OP-Players"
  LoginMessage:
    Name: "&6Verander De LoginMessage"
  LogoutMessage:
    Name: "&6Verander De LogoutMessage"
  ReloadMenu:
    ReloadPlugin:
      Name: "&c%diamond% &6Reload de plugin"
    ReloadServer:
      Name: "&c%diamond% &6Reload de server"
  CommandSpy:
    Name: "&6Verander de CommandSpy status"
    EnchantedIfEnabled: "True" #alleen True of False (ja & nee)

#ServerManager MOET hier blijven staan.
ignored-plugins: [ServerManager]